version: "2"
services:
  webserver:
    image: danpoltawski/moodle-php-apache:7.0
    ports:
      - "8000:80"
    depends_on:
      - db
      - mail
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html"
    environment:
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_BROWSER: firefox
  db:
    image: postgres:9
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: "m@0dl3ing"
      POSTGRES_DB: moodle
  selenium:
    image: selenium/standalone-firefox:2.53.1
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html:ro"
  mail:
    image: tophfr/mailcatcher
    ports:
      - "2525:80"
