version: "2"
services:
  webserver:
    environment:
      MOODLE_DOCKER_DBTYPE: mariadb
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin
  db:
    image: mariadb:10.2
    volumes:
      - ./assets/mysql:/docker-entrypoint-initdb.d:ro
      - data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin
      --innodb_file_per_table=On
      --wait-timeout=28800
      --innodb_large_prefix=On
      --max_allowed_packet=512M
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: moodle
      MYSQL_PASSWORD: "m@0dl3ing"
      MYSQL_DATABASE: moodle
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: moodledocker_phpmyadmin_1
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=
    restart: always
    ports:
      - 8001:80
    volumes:
      - /sessions
volumes:
  data:
    driver: "local"
