#!/bin/bash

touch /var/www/html/imadethis

mysql --user=root --execute="CREATE DATABASE moodle DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

mysql --user=root --execute="GRANT ALL PRIVILEGES ON moodle.* TO 'moodle'@'localhost' IDENTIFIED BY 'test'; FLUSH PRIVILEGES;"

# create the default database from the ADDed file.
mysql -u root -D moodle < /tmp/new_moodle_instance.sql
